version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - /Applications/
      - /Tests
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
  - package-ecosystem: npm
    directories:
      - "/Applications/Spark.Web.R4/app/"
      - "/Applications/Spark.Web.STU3/app/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
    groups:
      applications-npm:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      applications-npm-major:
        patterns:
          - "*"
        update-types:
          - "major"
  - package-ecosystem: docker
    directory: "/.docker/linux"
    schedule:
      interval: weekly
    commit-message:
      prefix: "Docker:"
  - package-ecosystem: github-actions
    directory: "/.github/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "CI:"
