{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.mongodb.fullname" . }}
  labels:
    {{- include "spark.mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "spark.mongodb.selectorLabels" . | nindent 4 }}
{{- end }}
