apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark.fullname" . }}-secrets
  labels:
    {{- include "spark.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-connection-string: {{ include "spark.mongodb.connectionString" . | quote }}
