  
name: Gatsby build

on:
  push:
      paths:
        - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        working-directory: ./docs
        run: npm install

      - name: Run tests
        working-directory: ./docs
        continue-on-error: false
        run: npm run test

      - name: Build pages
        working-directory: ./docs
        run: npx gatsby build --prefix-paths