name: Docker Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Spark Docker image
        run: docker build . --file .docker/linux/Spark.Dockerfile 
          -t ${{ secrets.DOCKERHUB_ORGANIZATION }}/spark:${{steps.vars.outputs.tag}}
          -t ${{ secrets.DOCKERHUB_ORGANIZATION }}/spark:stu3-latest-develop
      - name: Push the tagged Spark Docker image
        run: docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/spark
      - name: Build the tagged Mongo Docker image
        run: docker build . --file .docker/linux/Mongo.Dockerfile 
          -t ${{ secrets.DOCKERHUB_ORGANIZATION }}/mongo:${{steps.vars.outputs.tag}}
          -t ${{ secrets.DOCKERHUB_ORGANIZATION }}/mongo:stu3-latest-develop
      - name: Push the tagged Mongo Docker image
        run: docker push ${{ secrets.DOCKERHUB_ORGANIZATION }}/mongo
