name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install npm dependencies
        working-directory: ./docs
        run: npm install

      - name: Run tests
        working-directory: ./docs
        run: npm run test

      - name: Build pages
        working-directory: ./docs
        run: npx gatsby build --prefix-paths 

      - name: Deploy pages from master
        working-directory: ./docs
        run: |
          git config --global user.name "Spark documentation bot"
          git config --global user.email "spark@docbot.com"
          npx gh-pages -d public -r https://${{ secrets.GH_TOKEN }}@github.com/FirelyTeam/spark.git
