name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: |
          dotnet pack "./src/Spark.Engine/Spark.Engine.csproj" -c Release
          dotnet pack "./src/Spark.Mongo/Spark.Mongo.csproj" -c Release
      - name: Deploy Nuget Packages
        run: dotnet nuget push .\src\**\*.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --no-symbols
