name: Release

on:
  release:
    types: [published]

jobs:
  build:
    if: github.repository == 'FirelyTeam/spark'

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: |
          dotnet pack "./Libraries/Spark.Engine/Spark.Engine.csproj" -c Release
          dotnet pack "./Libraries/Spark.Engine.STU3/Spark.Engine.STU3.csproj" -c Release
          dotnet pack "./Libraries/Spark.Engine.R4/Spark.Engine.R4.csproj" -c Release
          dotnet pack "./Libraries/Spark.Store.MongoDB/Spark.Store.MongoDB.csproj" -c Release
      - name: Deploy Nuget Packages
        run: dotnet nuget push .\Libraries\**\*.nupkg
          --api-key ${{ secrets.NUGET_API_KEY }}
          --skip-duplicate
          --source https://api.nuget.org/v3/index.json
          --no-symbols
