name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    if: github.repository == 'FirelyTeam/spark'

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-24.04, macos-14, macos-14-large ]

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Unit tests
        run: |
          dotnet test "./Tests/Spark.Engine.STU3.Tests/Spark.Engine.STU3.Tests.csproj"
          dotnet test "./Tests/Spark.Engine.R4.Tests/Spark.Engine.R4.Tests.csproj"
          dotnet test "./Tests/Spark.Store.MongoDB.Tests/Spark.Store.MongoDB.Tests.csproj"
          dotnet test "./Tests/Spark.Web.STU3.Tests/Spark.Web.STU3.Tests.csproj"
          dotnet test "./Tests/Spark.Web.R4.Tests/Spark.Web.R4.Tests.csproj"
